#!/bin/bash

if [ "$2" = "from" ]
    then
      for i in `grep $1 /var/log/maillog* | awk '{print $6}' | grep -v NOQUEUE `; do grep $i /var/log/maillog* ;done |awk '{ if (match($0,/from=<.*>/,m)) print $1" "$2" "$3" " m[0] }'
else
      for i in `grep $1 /var/log/maillog* | awk '{print $6}' | grep -v NOQUEUE `; do grep $i /var/log/maillog* ;done |awk '{ if (match($0,/to=<.*>/,m)) print $1" "$2" "$3" " m[0] }'
fi

